import {defaults,loads} from './config.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function simulate(input={}){
 const c={...defaults,...input}, scenario=c.scenario||'Evening renewable drop', rows=[]; let soc=clamp(+c.startSoc||74,20,95)/100*c.batteryKwh, maxSoc=.95*c.batteryKwh,minSoc=.2*c.batteryKwh, baselineUn=0,flexUn=0,baseGrid=0,flexGrid=0,renGen=0,renUsed=0,baseRenUsed=0,curtail=0,baseCritical=0,flexCritical=0,criticalReq=0,flexServed=0,baseServed=0,throughput=0,peak=0,basePeak=0, outage=0,baseOutage=0,respKwh=0;
 for(let i=0;i<c.hours*4;i++){const h=i/4, t=String(Math.floor(h)).padStart(2,'0')+':'+String(Math.round((h%1)*60)).padStart(2,'0');
  const morning=Math.exp(-(((h-8)/2.2)**2)),evening=Math.exp(-(((h-20)/2.8)**2)); let demand=175+75*morning+155*evening+18*Math.sin(h*1.7)+((i*17)%13-6); demand*=c.households/500;
  const shortfallWindow=h>=16&&h<21;
  const cloud=(scenario==='Cloudy afternoon'&&h>12&&h<17?.42:scenario==='Extended renewable shortage'&&h>11&&h<21?.58:scenario==='Evening Renewable Shortfall'&&shortfallWindow?.2:scenario==='Normal sunny day'?.12:1);
  if(scenario==='Evening Renewable Shortfall'&&shortfallWindow) demand*=1.15;
  let solar=h<6||h>18?0:c.solarKw*Math.max(0,Math.sin(Math.PI*(h-6)/12))*cloud*(.94+.06*Math.sin(i*1.1));
  let wind=c.windKw*(.42+.2*Math.sin(i*.31)+.1*Math.cos(i*.83)); if(scenario==='Grid outage + renewable shortfall'&&h>17&&h<21) wind*=.5;
  const renewable=Math.max(0,solar+wind), net=demand-renewable, shortPct=Math.max(0,net/demand); let gridOk=c.gridAvailable&&!(scenario==='Grid outage + renewable shortfall'&&h>=17&&h<21);
  // Baseline serves critical demand first but has no coordinated storage or response.
  let bg=gridOk?Math.min(net, demand,c.gridImportLimitKw):0, bserved=Math.min(demand,renewable+bg), bun=demand-bserved; baseGrid+=bg*.25; baselineUn+=bun*.25; baseServed+=bserved*.25; basePeak=Math.max(basePeak,bg); if(bun>1)baseOutage+=.25;
  let shift=0; if(net>0&&shortPct>.12&&c.participation>0){shift=Math.min(net*.24, 30*c.participation);respKwh+=shift*.25;}
  let adjusted=demand-shift, fnet=Math.max(0,adjusted-renewable); let discharge=0,charge=0;
  if(fnet>0&&soc>minSoc){discharge=Math.min(30,fnet,(soc-minSoc)*.9*4);soc-=discharge*.25/.9;throughput+=discharge*.25;}
  if(renewable>adjusted&&soc<maxSoc){charge=Math.min(30,renewable-adjusted,(maxSoc-soc)*4/.9);soc+=charge*.25*.9;throughput+=charge*.25;}
  const fg=gridOk?Math.min(Math.max(0,fnet-discharge),demand,c.gridImportLimitKw):0, fserved=Math.min(adjusted,renewable+discharge+fg), flexEquivalentServed=Math.min(demand,fserved+shift), fun=Math.max(0,demand-flexEquivalentServed); flexGrid+=fg*.25;flexUn+=fun*.25;flexServed+=flexEquivalentServed*.25;peak=Math.max(peak,fg);if(fun>1)outage+=.25;
  const critical=demand*.17; criticalReq+=critical*.25; let criticalServed=Math.min(critical,renewable+discharge+fg);baseCritical+=Math.min(critical,renewable+bg)*.25;flexCritical+=criticalServed*.25;
  renGen+=renewable*.25; baseRenUsed+=Math.min(renewable,demand)*.25; let used=Math.min(renewable,adjusted+charge);renUsed+=used*.25;curtail+=Math.max(0,renewable-adjusted-charge)*.25;
  rows.push({time:t,demand:+demand.toFixed(1),renewable:+renewable.toFixed(1),solar:+solar.toFixed(1),wind:+wind.toFixed(1),forecast:+(renewable*(1+.02*Math.sin(i))).toFixed(1),lower:+(renewable*.86).toFixed(1),upper:+(renewable*1.14).toFixed(1),soc:+(soc/c.batteryKwh*100).toFixed(1),grid:+fg.toFixed(1),baselineGrid:+bg.toFixed(1),charge:+charge.toFixed(1),discharge:+discharge.toFixed(1),response:+shift.toFixed(1),severity:shortPct>.4?'CRITICAL':shortPct>.25?'HIGH':shortPct>.1?'MEDIUM':net>0?'LOW':'NONE',criticalLoad:+(critical).toFixed(1),criticalServed:+(critical?criticalServed/critical*100:100).toFixed(1),batteryAvailable:+Math.max(0,(soc-minSoc)*.9*4).toFixed(1),flexAvailable:+(loads.filter(x=>x.flex).reduce((a,x)=>a+x.kw,0)*c.households/500*c.participation).toFixed(1),gridAvailable:gridOk});
 }
 const totalDemand=rows.reduce((a,r)=>a+r.demand*.25,0), basePeakCost=rows.reduce((a,r)=>a+(r.baselineGrid>0&&+r.time.slice(0,2)>=17&&+r.time.slice(0,2)<22?r.baselineGrid*.25*(c.peakTariff-c.tariff):0),0), costBase=baseGrid*c.tariff+basePeakCost; let costFlex=flexGrid*c.tariff; const availability=(served,un)=>100*served/(served+un||1), baseAvail=availability(baseServed,baselineUn),flexAvail=availability(flexServed,flexUn), baseCrit=100*baseCritical/(criticalReq||1),flexCrit=100*flexCritical/(criticalReq||1);
 const peakCost=rows.reduce((a,r)=>a+(r.grid>0&&+r.time.slice(0,2)>=17&&+r.time.slice(0,2)<22?r.grid*.25*(c.peakTariff-c.tariff):0),0); costFlex+=peakCost;
 const batteryAvailable=Math.max(0,(rows[72]?.batteryAvailable||0));
 const latest=rows[72]||rows[0], predictedShortfall=Math.max(0,latest.demand-latest.forecast);
 const decisions={alert:latest.severity==='HIGH'||latest.severity==='CRITICAL'||predictedShortfall>0, predictedShortfall:+predictedShortfall.toFixed(1),batteryDischarge:latest.discharge,waterPumpDelayMinutes:latest.response>0?15:0,evShiftMinutes:latest.response>0?30:0,criticalProtected:latest.criticalServed>=99,reasoning:['Critical loads have highest priority.','Forecast renewable generation is compared with demand.','Battery dispatch is limited by available energy and power.','Flexible demand response follows configured participation.','Grid import supplies remaining demand when available.']};
 const reliability={baseline:{availability:+baseAvail.toFixed(2),unservedKwh:+baselineUn.toFixed(1),outageHours:+baseOutage.toFixed(2),criticalAvailability:+baseCrit.toFixed(2),renewableUtilization:+(100*baseRenUsed/(renGen||1)).toFixed(1),gridImportKwh:+baseGrid.toFixed(1),peakGridKw:+basePeak.toFixed(1),batteryThroughputKwh:0,cost:+costBase.toFixed(0)},gridFlex:{availability:+flexAvail.toFixed(2),unservedKwh:+flexUn.toFixed(1),outageHours:+outage.toFixed(2),criticalAvailability:+flexCrit.toFixed(2),renewableUtilization:+(100*renUsed/(renGen||1)).toFixed(1),gridImportKwh:+flexGrid.toFixed(1),peakGridKw:+peak.toFixed(1),batteryThroughputKwh:+throughput.toFixed(1),cost:+costFlex.toFixed(0)}};
 return {config:c,rows,loads,decisions,reliability,summary:{totalDemand:+totalDemand.toFixed(1),renewableGenerated:+renGen.toFixed(1),renewableUsed:+renUsed.toFixed(1),curtailment:+curtail.toFixed(1),baselineGrid:+baseGrid.toFixed(1),gridImport:+flexGrid.toFixed(1),batteryThroughput:+throughput.toFixed(1),unservedBaseline:+baselineUn.toFixed(1),unservedGridFlex:+flexUn.toFixed(1),preventedUnservedKwh:+Math.max(0,baselineUn-flexUn).toFixed(1),outageHoursBaseline:+baseOutage.toFixed(2),outageHoursGridFlex:+outage.toFixed(2),availabilityBaseline:+baseAvail.toFixed(2),availabilityGridFlex:+flexAvail.toFixed(2),availabilityImprovement:+(flexAvail-baseAvail).toFixed(2),criticalBaseline:+baseCrit.toFixed(2),criticalGridFlex:+flexCrit.toFixed(2),renewableUtilizationBaseline:+(100*baseRenUsed/(renGen||1)).toFixed(1),renewableUtilization:+(100*renUsed/(renGen||1)).toFixed(1),peakGridBaseline:+basePeak.toFixed(1),peakGridFlex:+peak.toFixed(1),responseKwh:+respKwh.toFixed(1),costBaseline:+costBase.toFixed(0),costGridFlex:+costFlex.toFixed(0),dailySavings:+Math.max(0,costBase-costFlex).toFixed(0),socEnd:+(soc/c.batteryKwh*100).toFixed(1),cycles:+(throughput/(2*c.batteryKwh)).toFixed(2),batteryAvailableKwh:+batteryAvailable.toFixed(1)},economics:{tariff:c.tariff,annualizedSavings:+(Math.max(0,costBase-costFlex)*365).toFixed(0)},decisions, reliability};
}
