import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, LineChart, Line } from 'recharts';
import { Activity, Sun, Wind, BatteryCharging, Zap, LayoutDashboard, CloudSun, SlidersHorizontal, ChartNoAxesCombined, Wallet, Users, Network, Settings, Play, RotateCcw, AlertTriangle, Leaf, ChevronRight, Pause, Droplets, CarFront, Lightbulb, Hospital, HelpCircle } from 'lucide-react';
import './style.css';

const nav = [['Overview', LayoutDashboard], ['Forecast', CloudSun], ['Demand response', Activity], ['Storage', BatteryCharging], ['Reliability', ChartNoAxesCombined], ['Economics', Wallet], ['Simulation', SlidersHorizontal], ['Digital Twin', Network], ['Resident view', Users], ['Architecture', Network], ['Settings', Settings]];
const initialForm = { households: 500, solarKw: 250, windKw: 50, batteryKwh: 500, startSoc: 74, participation: .75, gridAvailable: true };
const fmt = (n, d = 1) => Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: d });
const money = n => '₹' + Math.round(n || 0).toLocaleString('en-IN');

function App() {
  const [data, setData] = useState(null), [page, setPage] = useState('Overview'), [scenario, setScenario] = useState('Evening renewable drop'), [form, setForm] = useState(initialForm), [busy, setBusy] = useState(false), [running, setRunning] = useState(false), [paused, setPaused] = useState(false), [step, setStep] = useState(0), [why, setWhy] = useState(false), [selected, setSelected] = useState('Solar');
  const [assumptions, setAssumptions] = useState({ batteryCost: 2500000, serviceCost: 120000, maintenance: 75000, tariff: 8, batteryLife: 10 });
  const load = async () => { try { const r = await fetch('/api/simulation'); if (!r.ok) throw Error('API unavailable'); setData(await r.json()); } catch (e) { console.error(e); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!running || paused) return; const timer = setInterval(() => setStep(s => { if (s >= 95) { setRunning(false); return 95; } return s + 1; }), 150); return () => clearInterval(timer); }, [running, paused]);
  const run = async (shortfall = false) => { setBusy(true); try { const body = { ...form, scenario: shortfall ? 'Evening Renewable Shortfall' : scenario }; if (shortfall) setScenario(body.scenario); const r = await fetch('/api/simulation/run', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok) throw Error((await r.json()).error || 'Simulation failed'); setData(await r.json()); setStep(shortfall ? 63 : 0); setPaused(false); setRunning(shortfall); } catch (e) { console.error(e); } finally { setBusy(false); } };
  const reset = async () => { setRunning(false); setPaused(false); setStep(0); setScenario('Evening renewable drop'); setForm(initialForm); const r = await fetch('/api/simulation/reset', { method: 'POST' }); if (r.ok) setData(await r.json()); };
  if (!data) return <div className="loading">Connecting to neighbourhood simulation…</div>;
  const rows = data.rows || [], s = data.summary || {}, live = rows[Math.min(step, rows.length - 1)] || rows[0] || {}, metrics = data.reliability || {};
  const twinIndex = running || (scenario === 'Evening Renewable Shortfall' && step > 63) ? Math.max(63, step) : (scenario === 'Evening Renewable Shortfall' ? Math.max(63, step) : 72);
  const now = rows[Math.min(twinIndex, rows.length - 1)] || live;
  const status = now.severity === 'CRITICAL' ? 'Critical' : now.severity === 'HIGH' || now.severity === 'MEDIUM' ? 'Attention' : 'Normal';
  const summaryRows = [
    ['Supply availability', metrics.baseline?.availability, metrics.gridFlex?.availability, '%', true],
    ['Unserved energy', metrics.baseline?.unservedKwh, metrics.gridFlex?.unservedKwh, 'kWh', false],
    ['Outage duration', metrics.baseline?.outageHours, metrics.gridFlex?.outageHours, 'h', false],
    ['Critical-load availability', metrics.baseline?.criticalAvailability, metrics.gridFlex?.criticalAvailability, '%', true],
    ['Renewable utilization', metrics.baseline?.renewableUtilization, metrics.gridFlex?.renewableUtilization, '%', true],
    ['Grid import', metrics.baseline?.gridImportKwh, metrics.gridFlex?.gridImportKwh, 'kWh', false],
    ['Peak grid demand', metrics.baseline?.peakGridKw, metrics.gridFlex?.peakGridKw, 'kW', false],
    ['Battery throughput', metrics.baseline?.batteryThroughputKwh, metrics.gridFlex?.batteryThroughputKwh, 'kWh', true],
    ['Estimated operating cost', metrics.baseline?.cost, metrics.gridFlex?.cost, '₹', false, true]
  ].map(([name, baseline, gridFlex, unit, higher, currency]) => ({ name, baseline: +baseline || 0, gridFlex: +gridFlex || 0, unit, higher, currency, improvement: (higher ? (gridFlex || 0) - (baseline || 0) : (baseline || 0) - (gridFlex || 0)) }));
  const benefit = Math.max(0, s.preventedUnservedKwh || 0);
  const props = { data, rows, s, now, status, form, setForm, scenario, setScenario, run, reset, busy, running, paused, setPaused, step, setStep, why, setWhy, selected, setSelected, assumptions, setAssumptions, summaryRows, benefit, setPage };
  return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandicon"><Zap size={20} /></div><div><b>GridFlex</b><small>NEIGHBOURHOOD</small></div></div><div className="district"><span className="dot green" /> Demo community <ChevronRight size={14} /><small>{data.config?.households || 500} households · India</small></div><div className="navlabel">WORKSPACE</div>{nav.map(([name, Icon]) => <button key={name} className={'navitem ' + (page === name ? 'active' : '')} onClick={() => setPage(name)}><Icon size={17} />{name}</button>)}<div className="sidebottom"><div className="avatar">GF</div><div><b>Community operator</b><small>Operator account</small></div></div></aside>
    <main className="main"><header><div><div className="crumb">GRIDFLEX <span>/</span> {page.toUpperCase()}</div><h1>{page === 'Overview' ? 'Neighbourhood overview' : page}</h1></div><div className="header-right"><span className="demo"><i /> SIMULATED SCENARIO</span><button className="iconbtn" onClick={reset} title="Reset simulation"><RotateCcw size={16} /></button></div></header>
      {page === 'Digital Twin' ? <DigitalTwin {...props} /> : page === 'Reliability' ? <Comparison {...props} /> : page === 'Economics' ? <Economics {...props} /> : page === 'Simulation' ? <Simulation {...props} /> : page === 'Forecast' ? <Forecast {...props} /> : page === 'Demand response' || page === 'Storage' ? <Operations {...props} page={page} /> : page === 'Resident view' ? <Resident {...props} /> : page === 'Architecture' ? <Architecture /> : page === 'Settings' ? <SettingsPage form={form} /> : <Dashboard {...props} />}
      <footer>Results are calculated from a simulated scenario. Prototype assumptions; not a dispatch guarantee or a market price estimate.</footer></main></div>;
}

function Status({ status, now }) { return <div className={'statusbar ' + (status === 'Normal' ? 'stable' : status === 'Attention' ? 'watch' : 'critical')}><div className="statusicon">{status === 'Normal' ? <Activity size={18} /> : <AlertTriangle size={18} />}</div><div><b>{status === 'Normal' ? 'Supply stable' : status === 'Attention' ? 'Renewable shortfall predicted' : 'Critical supply shortage'}</b><small>{now.time} · Demand {fmt(now.demand)} kW against {fmt(now.renewable)} kW renewable generation</small></div><span className="statuspill">{status.toUpperCase()}</span></div>; }
function Intelligence({ now, data, why, setWhy }) {
  const shortfall = Math.max(0, now.demand - now.forecast), flex = now.flexAvailable || 0;
  return <section className="panel intelligence"><div className="panelhead"><div><h2>⚡ GridFlex Intelligence</h2><p>Decision Engine · Forecasting Engine · Optimization Logic</p></div><span className={'badge ' + (shortfall > 0 ? 'amber' : 'greenbadge')}>{shortfall > 0 ? 'SHORTFALL PREDICTED' : 'BALANCED'}</span></div><div className="intelstats"><div><small>Current demand</small><b>{fmt(now.demand)} kW</b></div><div><small>Renewable generation</small><b>{fmt(now.renewable)} kW</b></div><div><small>Predicted shortfall</small><b>{fmt(shortfall)} kW</b></div><div><small>Battery available</small><b>{fmt(now.batteryAvailable)} kWh</b></div><div><small>Flexible load available</small><b>{fmt(flex)} kW</b></div><div><small>Critical load requirement</small><b>{fmt(now.criticalLoad)} kW</b></div></div><h3>Recommended actions</h3><div className="recommendations"><span>🔋 Battery discharge: <b>{fmt(now.discharge)} kW</b></span><span>🚿 Water pumping: <b>{now.response > 0 ? 'delay 15 min' : 'available'}</b></span><span>🚗 EV charging: <b>{now.response > 0 ? 'shift 30 min' : 'available'}</b></span><span>💡 Critical loads: <b>{now.criticalServed >= 99 ? 'protected' : `${fmt(now.criticalServed)}% served`}</b></span></div><button className="textbtn" onClick={() => setWhy(!why)}><HelpCircle size={14} /> {why ? 'Hide reasoning' : 'Why this decision?'}</button>{why && <div className="why"><b>WHY?</b><ol>{(data.decisions?.reasoning || []).map(x => <li key={x}>{x}</li>)}</ol><small>Rule-based and profile-based prototype logic; no advanced AI is claimed.</small></div>}</section>;
}
function Dashboard(p) { const { rows, s, now, status, setPage } = p; return <><Status status={status} now={now} /><section className="metricgrid">{[['Current demand', now.demand, 'kW', Zap], ['Renewable generation', now.renewable, 'kW', Sun], ['Battery state', now.soc, '%', BatteryCharging], ['Grid import', now.grid, 'kW', Activity], ['Renewable utilization', s.renewableUtilization, '%', Leaf], ['Critical load served', now.criticalServed, '%', Hospital]].map(([title, value, unit, Icon]) => <div className="metric" key={title}><div className="metric-top"><span>{title}</span><Icon size={17} /></div><div className="metric-value">{fmt(value)}<small>{unit}</small></div><div className="metric-foot">Calculated from simulated profile</div></div>)}</section><div className="contentgrid"><div className="panel"><div className="panelhead"><div><h2>Demand & renewable supply</h2><p>24-hour profile · 15-minute intervals</p></div></div><Series rows={rows} /></div><DigitalTwinGraphic {...p} compact /></div><Intelligence {...p} /><section className="panel compare-preview"><div className="panelhead"><div><h2>Baseline vs GridFlex</h2><p>Calculated from simulated scenario</p></div><button className="textbtn" onClick={() => setPage('Reliability')}>Full comparison →</button></div><div className="kpi"><span>Reliability Improvement</span><b>{fmt(s.availabilityImprovement, 2)} <small>percentage points</small></b></div><ComparisonTable rows={p.summaryRows.slice(0, 5)} /></section><button className="primary" onClick={() => setPage('Digital Twin')}>Open Digital Twin →</button></>; }
function Series({ rows }) { return <div className="chart"><ResponsiveContainer><AreaChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="time" interval={11} /><YAxis /><Tooltip /><Legend /><Area dataKey="demand" name="Demand (kW)" stroke="#243b53" fill="#dce5ee" /><Area dataKey="renewable" name="Renewable (kW)" stroke="#21a179" fill="#c9efe2" /></AreaChart></ResponsiveContainer></div>; }
const stages = ['FORECAST', 'SHORTFALL DETECTED', 'BATTERY RESPONSE', 'LOAD SHIFTING', 'DEMAND RESPONSE', 'CRITICAL LOAD PROTECTION', 'GRID SUPPORT', 'RESULT'];
function ShortfallControls(p) { return <div className="buttonrow"><button className="primary" onClick={() => p.run(true)} disabled={p.busy || p.running}><Play size={16} />{p.busy ? 'Running…' : 'Run Shortfall Simulation'}</button><button className="secondary" onClick={() => p.setPaused(!p.paused)} disabled={!p.running}>{p.paused ? <Play size={15} /> : <Pause size={15} />}{p.paused ? 'Resume' : 'Pause'}</button><button className="secondary" onClick={p.reset}><RotateCcw size={16} />Reset</button></div>; }
function stageIndex(step) { return Math.min(stages.length - 1, Math.floor(Math.max(0, step - 63) / 32 * (stages.length - 1))); }
function DigitalTwin(p) { return <><Status status={p.status} now={p.now} /><div className="simintro"><div><span className="eyebrow">LIVE SIMULATION STATE</span><h2>🏘️ Neighbourhood Digital Twin</h2><p>Every component below reads the current shared simulation result.</p></div></div><ShortfallControls {...p} /><DigitalTwinGraphic {...p} /><Intelligence {...p} /><Timeline {...p} /><ResultBanner {...p} /></>; }
function DigitalTwinGraphic(p) {
  const { now, data, selected, setSelected, compact } = p; const loads = data.loads || [];
  const components = [
    { name: 'Solar', icon: Sun, power: now.solar, status: now.solar < (p.form.solarKw * .2) ? 'attention' : 'normal', priority: 'Generation', action: now.solar < p.form.solarKw * .2 ? 'Reduced output' : 'Generating' },
    { name: 'Wind', icon: Wind, power: now.wind, status: 'normal', priority: 'Generation', action: 'Generating' },
    { name: 'Households', icon: Users, power: Math.max(0, now.demand - loads.reduce((a, x) => a + x.kw, 0) * (p.form.households / 500)), status: 'normal', priority: 'Standard', action: 'Consuming' },
    { name: 'Shared Battery', icon: BatteryCharging, power: now.discharge || now.charge, status: now.discharge ? 'discharging' : now.charge ? 'charging' : 'normal', priority: 'Dispatchable', action: now.discharge ? 'Discharging' : now.charge ? 'Charging' : `${fmt(now.soc)}% SOC` },
    { name: 'Water Pump', icon: Droplets, power: loads.find(x => x.name === 'Water pumps')?.kw || 28, status: now.response ? 'attention' : 'normal', priority: 'Flexible · P2', action: now.response ? 'Shifted' : 'Available' },
    { name: 'EV Charging', icon: CarFront, power: loads.find(x => x.name === 'EV charging')?.kw || 22, status: now.response ? 'attention' : 'normal', priority: 'Flexible · P4', action: now.response ? 'Charging delayed' : 'Available' },
    { name: 'Street Lighting', icon: Lightbulb, power: loads.find(x => x.name === 'Street lighting')?.kw || 9, status: 'normal', priority: 'P2', action: 'Serving' },
    { name: 'Critical Facility', icon: Hospital, power: now.criticalLoad, status: now.criticalServed >= 99 ? 'normal' : 'critical', priority: 'Critical · P1', action: now.criticalServed >= 99 ? 'Protected' : `${fmt(now.criticalServed)}% served` },
    { name: 'Grid', icon: Zap, power: now.grid, status: now.grid > 0 ? 'discharging' : 'normal', priority: 'Supply support', action: now.grid > 0 ? 'Supporting' : 'Standby' }
  ];
  return <section className={'panel twin ' + (compact ? 'compact' : '')}><div className="panelhead"><div><h2>🏘️ Neighbourhood Digital Twin</h2><p>Click a component for live power, priority and dispatch state</p></div><span className="live"><i /> {now.time} LIVE</span></div><div className="energyflow"><b>Solar {fmt(now.solar)} kW + Wind {fmt(now.wind)} kW</b><span>↓</span><b className="coordinator">GridFlex Energy Coordinator</b><span>↓</span><div className="flowtargets">Battery <i /> Loads <i /> Grid</div></div><div className="twin-grid">{components.map(({ name, icon: Icon, power, status, priority, action }) => <button key={name} onClick={() => setSelected(name)} className={'twin-node ' + status + (selected === name ? ' chosen' : '')}><Icon size={18} /><b>{name}</b><strong>{fmt(power)} kW</strong><small>{priority}</small><em>{action}</em></button>)}</div><div className="selected-info"><b>{selected}</b><span>{components.find(x => x.name === selected)?.action} · {fmt(components.find(x => x.name === selected)?.power)} kW</span></div></section>;
}
function Timeline(p) { const active = stageIndex(p.step); return <section className="panel"><div className="panelhead"><div><h2>Simulation response timeline</h2><p>Stages reflect the running simulation and current dispatch row</p></div></div><div className="timeline">{stages.map((label, i) => <div key={label} className={i < active ? 'done' : i === active ? 'current' : ''}><span>{i + 1}</span><b>{label}</b></div>)}</div>{p.running && <p className="muted">At {p.rows[p.step]?.time}: demand {fmt(p.rows[p.step]?.demand)} kW · renewables {fmt(p.rows[p.step]?.renewable)} kW · battery {fmt(p.rows[p.step]?.discharge)} kW · response {fmt(p.rows[p.step]?.response)} kW · grid {fmt(p.rows[p.step]?.grid)} kW</p>}</section>; }
function ResultBanner({ s, benefit, running }) { return !running ? <div className="result-banner"><b>{benefit > 0 ? `GridFlex prevented ${fmt(benefit)} kWh of unserved energy.` : `GridFlex prevented ${fmt(benefit)} kWh of unserved energy in this scenario.`}</b><span>GridFlex availability {fmt(s.availabilityGridFlex, 2)}% · Baseline {fmt(s.availabilityBaseline, 2)}%</span></div> : null; }
function ComparisonTable({ rows }) { return <div className="tablewrap"><table><thead><tr><th>Metric</th><th>Baseline</th><th>GridFlex</th><th>Improvement</th></tr></thead><tbody>{rows.map(r => <tr key={r.name}><td>{r.name}</td><td>{r.currency ? money(r.baseline) : fmt(r.baseline)} {r.currency ? '' : r.unit}</td><td>{r.currency ? money(r.gridFlex) : fmt(r.gridFlex)} {r.currency ? '' : r.unit}</td><td className={r.improvement >= 0 ? 'positive' : 'negative'}>{r.currency ? money(r.improvement) : `${r.improvement >= 0 ? '+' : ''}${fmt(r.improvement)} ${r.unit}`}</td></tr>)}</tbody></table></div>; }
function Comparison(p) { const { summaryRows, s } = p; const chartRows = summaryRows.filter(r => r.unit === '%').map(r => ({ metric: r.name.replace(' availability', '').replace('Critical-load', 'Critical load'), Baseline: r.baseline, GridFlex: r.gridFlex })); return <><div className="kpi hero-kpi"><span>Reliability Improvement</span><b>{fmt(s.availabilityImprovement, 2)} <small>percentage points</small></b><p>Calculated from simulated scenario</p></div><section className="panel"><div className="panelhead"><div><h2>Baseline vs GridFlex</h2><p>Baseline: uncoordinated supply · GridFlex: coordinated storage, flexibility and grid support</p></div></div><ComparisonTable rows={summaryRows} /><small className="assumptions">Calculated from simulated scenario. Improvement reflects favorable direction for each metric.</small></section><section className="panel"><div className="panelhead"><div><h2>Reliability before and after</h2><p>Availability, critical-load service and renewable utilization (%)</p></div></div><div className="chart tall"><ResponsiveContainer><BarChart data={chartRows} margin={{ bottom: 50 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="metric" angle={-15} textAnchor="end" interval={0} height={65} /><YAxis domain={[0, 100]} unit="%" /><Tooltip formatter={v => `${fmt(v)}%`} /><Legend /><Bar dataKey="Baseline" fill="#aebdc6" /><Bar dataKey="GridFlex" fill="#21a179" /></BarChart></ResponsiveContainer></div></section></>; }
function Simulation(p) { return <><div className="simintro"><div><span className="eyebrow">INTERACTIVE MODEL</span><h2>Stress-test the neighbourhood</h2><p>Configure prototype inputs, then compare the two operating modes on the same profile.</p></div></div><div className="simgrid"><div className="panel controls"><label>Scenario<select value={p.scenario} onChange={e => p.setScenario(e.target.value)}>{['Normal sunny day', 'Cloudy afternoon', 'Evening renewable drop', 'Evening Renewable Shortfall', 'High-demand evening', 'Extended renewable shortage', 'Grid outage + renewable shortfall'].map(x => <option key={x}>{x}</option>)}</select></label><ControlSliders {...p} /><div className="buttonrow"><button className="primary" onClick={() => p.run(false)} disabled={p.busy}><Play size={16} />{p.busy ? 'Running…' : 'Run comparison'}</button><button className="secondary" onClick={p.reset}><RotateCcw size={16} />Reset</button></div><ShortfallControls {...p} /></div><div className="panel simresult"><h2>Latest calculated result</h2><p>Paired baseline and GridFlex run</p><b>Availability: {fmt(p.s.availabilityBaseline, 2)}% → {fmt(p.s.availabilityGridFlex, 2)}%</b><p>Unserved energy: {fmt(p.s.unservedBaseline)} → {fmt(p.s.unservedGridFlex)} kWh</p><p>Critical availability: {fmt(p.s.criticalGridFlex)}%</p><p>Response energy: {fmt(p.s.responseKwh)} kWh</p><p>Grid import: {fmt(p.s.baselineGrid)} → {fmt(p.s.gridImport)} kWh</p><p>Cost estimate: {money(p.s.costBaseline)} → {money(p.s.costGridFlex)}</p></div></div><Timeline {...p} /><ResultBanner {...p} /><section className="panel"><h2>Dispatch through the day</h2><Series rows={p.rows} /></section></>; }
function ControlSliders({ form, setForm }) { const fields = [['Households', 'households', 50, 2000, 50, ' homes'], ['Solar capacity', 'solarKw', 0, 1000, 10, ' kW'], ['Wind capacity', 'windKw', 0, 300, 5, ' kW'], ['Battery capacity', 'batteryKwh', 50, 2000, 50, ' kWh'], ['Starting battery SOC', 'startSoc', 20, 95, 1, '%'], ['DR participation', 'participation', 0, 100, 5, '%']]; return <><div className="controlgrid">{fields.map(([label, key, min, max, step, unit]) => <label key={key}>{label}<div className="rangeval">{key === 'participation' ? Math.round(form[key] * 100) : form[key]}{unit}</div><input type="range" min={min} max={max} step={step} value={key === 'participation' ? form[key] * 100 : form[key]} onChange={e => setForm({ ...form, [key]: key === 'participation' ? +e.target.value / 100 : +e.target.value })} /></label>)}</div><label className="togglelabel"><input type="checkbox" checked={form.gridAvailable} onChange={e => setForm({ ...form, gridAvailable: e.target.checked })} /> Grid available</label></>; }
function Economics(p) { const { assumptions: a, setAssumptions: setA, data, s } = p; const daily = Math.max(0, s.dailySavings * a.tariff / Math.max(1, data.config.tariff)); const annualSavings = daily * 365, annualCost = a.serviceCost + a.maintenance, netAnnual = annualSavings - annualCost, investment = a.batteryCost, payback = netAnnual > 0 ? investment / netAnnual : null, energyReduction = s.costBaseline > 0 ? Math.max(0, (s.costBaseline - s.costGridFlex) / s.costBaseline * 100) : 0; const fields = [['Battery cost (₹)', 'batteryCost', 100000, 20000000, 50000], ['Software/service cost per year (₹)', 'serviceCost', 0, 5000000, 10000], ['Annual maintenance (₹)', 'maintenance', 0, 5000000, 10000], ['Electricity tariff (₹/kWh)', 'tariff', 1, 30, 0.5], ['Battery lifetime (years)', 'batteryLife', 1, 25, 1]]; return <><section className="panel"><div className="panelhead"><div><h2>💰 Community Economics</h2><p>Prototype assumptions — values are configurable and not guaranteed market prices.</p></div></div><div className="economic-inputs"><label>Number of households<input type="number" value={data.config.households} onChange={e => p.setForm({ ...p.form, households: +e.target.value })} /></label><label>Solar capacity (kW)<input type="number" value={data.config.solarKw} onChange={e => p.setForm({ ...p.form, solarKw: +e.target.value })} /></label><label>Battery capacity (kWh)<input type="number" value={data.config.batteryKwh} onChange={e => p.setForm({ ...p.form, batteryKwh: +e.target.value })} /></label>{fields.map(([label, key, min, max, step]) => <label key={key}>{label}<input type="number" min={min} max={max} step={step} value={a[key]} onChange={e => setA({ ...a, [key]: +e.target.value })} /></label>)}</div><button className="primary" onClick={() => p.run(false)}>Recalculate with current simulation inputs</button><div className="economic-kpis">{[['Initial investment', money(investment)], ['Annual operating cost', money(annualCost)], ['Estimated annual savings', money(annualSavings)], ['Estimated monthly savings', money(annualSavings / 12)], ['Cost per household', money(investment / Math.max(1, data.config.households))], ['Estimated payback', payback ? `${fmt(payback, 1)} years` : 'Not reached'], ['Battery utilization', `${fmt(s.cycles)} equivalent cycles/day`], ['Energy-cost reduction', `${fmt(energyReduction)}%`]].map(([l, v]) => <div key={l}><small>{l}</small><b>{v}</b></div>)}</div><small className="assumptions">Annual savings extrapolate this simulated daily import-cost difference across 365 days. Actual operation, tariffs, financing, degradation and market prices may differ. Battery lifetime: {a.batteryLife} years.</small></section><Ownership /></>; }
function Ownership() { return <section className="panel ownership"><h2>Ownership & Operations Model</h2><span className="badge amber">PROPOSED OPERATING MODEL</span><div className="ownership-flow"><b>COMMUNITY / LOCAL OPERATOR</b><span>↓</span><b>GRIDFLEX SOFTWARE</b><span>↓</span><b>ENERGY COORDINATION</b><span>↓</span><div>BATTERY <i /> SMART LOADS <i /> GRID</div></div><ul><li><b>Ownership:</b> Community or local energy operator.</li><li><b>Operations:</b> Local operator manages configuration and shared resources.</li><li><b>Maintenance:</b> Battery and infrastructure maintained through a suitable service provider.</li><li><b>Software:</b> GridFlex provides forecasting, coordination, monitoring and analytics.</li></ul></section>; }
function Forecast({ rows }) { return <><section className="panel"><h2>Forecasting Engine</h2><p>Profile-based generation forecast and illustrative ±14% bounds. This is statistical prototype logic, not trained AI.</p><div className="chart tall"><ResponsiveContainer><LineChart data={rows}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="time" interval={11} /><YAxis /><Tooltip /><Legend /><Line dataKey="forecast" name="Forecast (kW)" stroke="#347cba" /><Line dataKey="lower" name="Lower band" stroke="#98c7dd" /><Line dataKey="upper" name="Upper band" stroke="#98c7dd" /><Line dataKey="demand" name="Demand (kW)" stroke="#243b53" /></LineChart></ResponsiveContainer></div></section><Intelligence {...arguments[0]} /></>; }
function Operations(p) { const storage = p.page === 'Storage'; return <><Intelligence {...p} /><section className="panel"><h2>{storage ? 'Shared battery dispatch' : 'Flexible demand response'}</h2><p>Dispatch is taken from the same simulation result.</p><div className="metricgrid">{(storage ? [['Battery SOC', p.now.soc, '%'], ['Discharge', p.now.discharge, 'kW'], ['Charge', p.now.charge, 'kW'], ['Available energy', p.now.batteryAvailable, 'kWh']] : [['Demand response', p.now.response, 'kW'], ['Shifted energy', p.s.responseKwh, 'kWh'], ['Participation', p.data.config.participation * 100, '%'], ['Flexible capacity', p.now.flexAvailable, 'kW']]).map(([l, v, u]) => <div className="metric" key={l}><small>{l}</small><b className="metric-value">{fmt(v)}<small>{u}</small></b></div>)}</div></section></>; }
function Resident({ now, s, status }) { return <><Status status={status} now={now} /><section className="panel residentnotice"><h2>Community energy update</h2><p>Renewables are providing {fmt(now.renewable)} kW against {fmt(now.demand)} kW of demand. Critical facility service is {fmt(now.criticalServed)}%.</p><p>Estimated modeled daily import-cost difference: {money(s.dailySavings)} across this neighbourhood scenario.</p></section></>; }
function Architecture() { return <section className="panel architecture"><h2>Neighbourhood Energy Coordinator</h2><p>Forecast → Detect → Decide → Respond → Measure</p><div className="ownership-flow"><b>Households + shared assets</b><span>↓</span><b>Forecasting Engine</b><span>↓</span><b>GridFlex Energy Coordinator</b><span>↓</span><div>Battery · Smart loads · Grid support</div></div><p>Express API serves one in-memory simulation result to dashboard, comparison, intelligence, twin and economics experiences.</p></section>; }
function SettingsPage({ form }) { return <section className="panel"><h2>Prototype configuration</h2><div className="settingsgrid">{Object.entries(form).map(([k, v]) => <div key={k}><small>{k}</small><b>{String(v)}</b></div>)}</div><p className="muted">The Simulation page configures demand, generation, battery and response participation.</p></section>; }
createRoot(document.getElementById('root')).render(<App />);
